### PR TITLE
Added final result config

### PR DESCRIPTION
**Pull request by kiraitachi**
Hi I added a section where it displays what should be the result, since adding the Scheme it doesn't activated it automatically. It's necessary to activate the "Dracula Profile".

I hope this makes it clear for new users and they can make it work out of the box.

Thanks!

### CODE REVIEW

**Comment by thismat** [comment]
@kiraitachi Thanks for the addition. You're right, showing how to enable the color scheme for a profile might be helpful. I would rather not add an entire config though, maybe just a single profile example with the color scheme active? 

Thanks.

**Review by thismat — CHANGES_REQUESTED** [review]
Would prefer to only show a sample profile with the color scheme active instead of an entire config.

**Comment by kiraitachi** [comment]
Hi @thismat  yeah your right.

I only left the profile and scheme.

 I also added the "json" language markup to the content of the config, in order to enable syntax colors of the language in Github and make more clear in red where it ends or starts the changes needed.

Hope you like it better! 👍

**Review by thismat — APPROVED** [review]

**Comment by thismat** [comment]
Thanks @kiraitachi. Merging it in. Good call on the json formatting.

**Pull request merged**
